/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modele.dao.ConnexionBDD;
import modele.dao.DaoMiniExcursion;
import modele.metier.MiniExcursion;

/**
 *
 * @author Benjamin
 */
public class JDialogAjouter extends javax.swing.JDialog {

    /**
     * Creates new form JDialogAjouter
     * @param parent
     * @param modal
     */
    public JDialogAjouter(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jTextFieldCodeAjoute.setText("");
        jTextFieldLibelleAjouter.setText("");
        jTextFieldNbPlacesAjouter.setText("");
        jTextFieldTarifAjouter.setText("");
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCode = new javax.swing.JLabel();
        jLabelLibelle = new javax.swing.JLabel();
        jLabelNbPlaces = new javax.swing.JLabel();
        jLabelTarif = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabelTitrePrincipal = new javax.swing.JLabel();
        jLabelCodeAjout = new javax.swing.JLabel();
        jLabelLibelleAjout = new javax.swing.JLabel();
        jLabelNbPlacesAjout = new javax.swing.JLabel();
        jLabelTarifAjout = new javax.swing.JLabel();
        jTextFieldCodeAjoute = new javax.swing.JTextField();
        jTextFieldLibelleAjouter = new javax.swing.JTextField();
        jTextFieldNbPlacesAjouter = new javax.swing.JTextField();
        jTextFieldTarifAjouter = new javax.swing.JTextField();
        jButtonOk = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabelCode.setText("Code : ");

        jLabelLibelle.setText("Libellé :");

        jLabelNbPlaces.setText("NbPlaces :");

        jLabelTarif.setText("Tarif :");

        jTextField2.setText("code de l'excursion");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitrePrincipal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitrePrincipal.setText("Informations de l'excursion");
        jLabelTitrePrincipal.setMinimumSize(new java.awt.Dimension(200, 30));
        jLabelTitrePrincipal.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabelCodeAjout.setText("Code : ");

        jLabelLibelleAjout.setText("Libellé :");

        jLabelNbPlacesAjout.setText("NbPlaces :");

        jLabelTarifAjout.setText("Tarif :");

        jTextFieldCodeAjoute.setText("Code de l'excursion");
        jTextFieldCodeAjoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodeAjouteActionPerformed(evt);
            }
        });

        jTextFieldLibelleAjouter.setText("Description de l'excursion");

        jTextFieldNbPlacesAjouter.setText("Nombre de places");
        jTextFieldNbPlacesAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNbPlacesAjouterActionPerformed(evt);
            }
        });

        jTextFieldTarifAjouter.setText("Tarif de l'excursion");

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButton1.setText("anuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelCodeAjout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelLibelleAjout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNbPlacesAjout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTarifAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCodeAjoute)
                            .addComponent(jTextFieldLibelleAjouter)
                            .addComponent(jTextFieldNbPlacesAjouter)
                            .addComponent(jTextFieldTarifAjouter)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(121, Short.MAX_VALUE)
                        .addComponent(jLabelTitrePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(114, 114, 114))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitrePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodeAjout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldCodeAjoute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLibelleAjout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldLibelleAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbPlacesAjout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNbPlacesAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTarifAjout)
                    .addComponent(jTextFieldTarifAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOk)
                    .addComponent(jButton1))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodeAjouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodeAjouteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodeAjouteActionPerformed

    private void jTextFieldNbPlacesAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNbPlacesAjouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNbPlacesAjouterActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
      String codeExcursion = jTextFieldCodeAjoute.getText(); 
    String libelleExcursion = jTextFieldLibelleAjouter.getText();
    String nbPlacesStr = jTextFieldNbPlacesAjouter.getText();
    String tarifStr = jTextFieldTarifAjouter.getText();

    if (codeExcursion.isEmpty() || libelleExcursion.isEmpty() || nbPlacesStr.isEmpty() || tarifStr.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Tous les champs doivent être remplis.");
        return;
    }

    int nbPlacesInt;
    double tarifDouble;

    try {
        nbPlacesInt = Integer.parseInt(nbPlacesStr);
        tarifDouble = Double.parseDouble(tarifStr);
        
        if (nbPlacesInt <= 0 || tarifDouble <= 0) {
            JOptionPane.showMessageDialog(null, "Le nombre de places et le tarif doivent être positifs.");
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Veuillez entrer des valeurs numériques valides.");
        return;
    }

    try {
        insertIntoDatabase(codeExcursion, libelleExcursion, nbPlacesInt, tarifDouble);
        ((JFrameLesExcursions) getParent()).rechargerExcursions();
        this.dispose();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Erreur lors de l'ajout dans la base de données : " + ex.getMessage());
          // Pour voir l'erreur dans la console
    }
}
    private static void insertIntoDatabase(String codeExcursion, String libelleExcursion,int  nbPlaces, double tarif) throws SQLException {
        String sql = "INSERT INTO Excursion (Code, Libelle, NbPlaces, Tarif) VALUES (?, ?, ?, ?)";

        Connection connection = ConnexionBDD.getConnexion(); 
        PreparedStatement pstmt = connection.prepareStatement(sql);

        pstmt.setString(1, codeExcursion);
        pstmt.setString(2, libelleExcursion);
        pstmt.setInt(3, nbPlaces);
        pstmt.setDouble(4, tarif);

        pstmt.executeUpdate();
        JOptionPane.showMessageDialog(null, "Excursion ajoutée avec succès !");
    
        
       
    }//GEN-LAST:event_jButtonOkActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogAjouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogAjouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogAjouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogAjouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogAjouter dialog = new JDialogAjouter(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelCode;
    private javax.swing.JLabel jLabelCodeAjout;
    private javax.swing.JLabel jLabelLibelle;
    private javax.swing.JLabel jLabelLibelleAjout;
    private javax.swing.JLabel jLabelNbPlaces;
    private javax.swing.JLabel jLabelNbPlacesAjout;
    private javax.swing.JLabel jLabelTarif;
    private javax.swing.JLabel jLabelTarifAjout;
    private javax.swing.JLabel jLabelTitrePrincipal;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldCodeAjoute;
    private javax.swing.JTextField jTextFieldLibelleAjouter;
    private javax.swing.JTextField jTextFieldNbPlacesAjouter;
    private javax.swing.JTextField jTextFieldTarifAjouter;
    // End of variables declaration//GEN-END:variables
}
